version: '3.5'

networks:
  backend:
    driver: bridge

services:
  golang.test:
    container_name: golang
    image: golang:1.8
    build:
      context: ./golang
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "10000:22"
      - "8888:8888"
    networks:
      - backend
    stdin_open: true
    tty: true
    volumes:
      - '.:/whitebench'
    depends_on:
      - mysql.test
      - redis.test
  php8.test:
    container_name: php8.0
    image: php:8.0
    build:
      context: ./php8
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "10001:22"
    networks:
      - backend
    environment:
      - TZ=Asia/Shanghai
    stdin_open: true
    tty: true
    volumes:
      - './php8/logs:/var/log/php8'
      - '.:/whitebench'
      - './php8/etc/php81.ini:/usr/local/etc/php8/php81.ini'
    depends_on:
      - mysql.test
      - redis.test
  php81.test:
    container_name: php8.1
    image: php:8.1
    build:
      context: ./php81
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
      - "10004:22"
      - "5173:5173"
    networks:
      - backend
    environment:
      - TZ=Asia/Shanghai
    stdin_open: true
    tty: true
    volumes:
      - './php81/logs:/var/log/php'
      - '.:/whitebench'
      - './php81/etc/php81.ini:/usr/local/etc/php/php.ini'
    depends_on:
      - mysql.test
      - redis.test
      - mongodb
  php74.test:
    container_name: php7.4
    image: php:7.4
    build:
      context: ./php74
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
      - "10002:22"
    networks:
      - backend
    environment:
      - TZ=Asia/Shanghai
    stdin_open: true
    tty: true
    volumes:
      - './php74/logs:/var/log/php7.4'
      - '.:/whitebench'
      - './php74/etc/php7.4.ini:/usr/local/etc/php7.4/php7.4.ini'
    depends_on:
      - mysql.test
      - redis.test
#  php72.test:
#    container_name: php7.2
#    image: php:7.2
#    build:
#      context: php72
#      dockerfile: Dockerfile
#    ports:
#      - "8083:8083"
#      - "10003:22"
#    networks:
#      - backend
#    environment:
#      - TZ=Asia/Shanghai
#    stdin_open: true
#    tty: true
#    volumes:
#      - './php72/logs:/var/log/php7.1'
#      - '.:/whitebench'
#      - './php72/etc/php7.2.ini:/usr/local/etc/php7.1/php7.2.ini'
#    depends_on:
#      - mysql.test
#      - redis.test
  mysql.test:
    container_name: mysql8.0
    image: mysql:8.0
    build:
      context: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - './mysql/data:/var/lib/mysql'
      - './mysql/conf:/etc/mysql/conf.d'
    ports:
      - "3306:3306"
    networks:
      - backend
  redis.test:
    container_name: redis_dev
    image: redis:5.0
    build: ./redis
    volumes:
      - '/data/redis:/data'
    ports:
      - "6379:6379"
    networks:
      - backend
  mongodb:
    container_name: mongodb
    image: mongo:5.0.5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - '/data/mongodb:/data'
    networks:
      - backend